// SPDX-License-Identifier: MIT OR Apache-2.0
//! Differential and property tests for the curve math.
//!
//! THE REFERENCE IS NOT THIS CODE. `tests/vectors/mul_div.txt` is generated by
//! `tests/gen_vectors.py` using Python's arbitrary-precision integers, so the
//! implementation is checked against a different language's arithmetic. A
//! differential test whose reference shares the implementation's assumptions
//! proves only that the implementation agrees with itself.
//!
//! Half the vectors are cases where the exact quotient does NOT fit in 128
//! bits. Those are the interesting ones: the implementation must refuse them
//! by name rather than return a truncated number.

use antumbra::*;

/// One line of the Python-generated oracle: `a`, `b`, `d`, then the exact
/// floor and ceiling quotients, or `None` where the true quotient does not fit
/// in 128 bits and the implementation must refuse by name rather than truncate.
type Vector = (u128, u128, u128, Option<u128>, Option<u128>);

fn vectors() -> Vec<Vector> {
    let raw = include_str!("vectors/mul_div.txt");
    raw.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| {
            let f: Vec<&str> = l.split_whitespace().collect();
            let p = |s: &str| {
                if s == "-" {
                    None
                } else {
                    Some(s.parse::<u128>().unwrap())
                }
            };
            (
                f[0].parse().unwrap(),
                f[1].parse().unwrap(),
                f[2].parse().unwrap(),
                p(f[3]),
                p(f[4]),
            )
        })
        .collect()
}

#[test]
fn mul_div_matches_python_arbitrary_precision() {
    let v = vectors();
    assert!(v.len() >= 4000, "only {} vectors", v.len());
    let (mut in_range, mut refused) = (0u32, 0u32);
    for (a, b, d, want_floor, want_ceil) in v {
        match (mul_div_floor(a, b, d), want_floor) {
            (Ok(got), Some(w)) => {
                assert_eq!(got, w, "floor({a},{b},{d})");
                in_range += 1
            }
            (Err(CurveError::Overflow), None) => refused += 1,
            (Ok(g), None) => {
                panic!("returned {g} where the exact quotient exceeds u128: {a},{b},{d}")
            }
            (Err(e), Some(w)) => {
                panic!("refused {e:?} where the exact quotient is {w}: {a},{b},{d}")
            }
            (Err(e), None) => panic!("wrong refusal {e:?} for {a},{b},{d}"),
        }
        if let (Ok(got), Some(w)) = (mul_div_ceil(a, b, d), want_ceil) {
            assert_eq!(got, w, "ceil({a},{b},{d})");
        }
    }
    assert!(
        in_range > 1500 && refused > 1500,
        "the vector set must exercise both sides: {in_range} in range, {refused} refused"
    );
}

#[test]
fn k_does_not_fit_in_u128_for_an_eighteen_decimal_pair() {
    // The finding this crate exists for. Both reserves are ordinary values for
    // an 18-decimal token; their product is not representable in u128, so a
    // program that stores `k` as the RFP's reference text describes cannot be
    // written for this pair.
    let vt: u128 = 1_000_000_000 * 10u128.pow(18); // 1e9 tokens
    let vc: u128 = 1_000_000 * 10u128.pow(18); // 1e6 collateral
    assert!(vt.checked_mul(vc).is_none(), "k unexpectedly fit in u128");

    // The curve prices it regardless, because k is never materialised: each
    // formula folds into one mul_div with a 256-bit intermediate.
    let c = Curve::new(vt, vc, 500_000_000 * 10u128.pow(18)).unwrap();
    let out = c
        .quote_buy(1_000 * 10u128.pow(18))
        .expect("pricing must not overflow");
    assert!(out > 0, "an 18-decimal pair must be priceable");
}

#[test]
fn buy_never_pays_out_more_than_the_exact_value() {
    // Rounding must favour the pool. We compare against the exact result
    // computed from the vector file's own arithmetic domain by reconstructing
    // it with u128-safe parameters.
    let cases = [
        (10u128.pow(24), 10u128.pow(21), 10u128.pow(23)),
        (10u128.pow(18), 10u128.pow(15), 10u128.pow(17)),
        (10u128.pow(30), 10u128.pow(27), 10u128.pow(29)),
    ];
    for (vt, vc, d) in cases {
        let c = Curve::new(vt, vc, d).unwrap();
        for c_in in [1u128, 7, 10u128.pow(9), 10u128.pow(15), vc / 3, vc] {
            if let Ok(out) = c.quote_buy(c_in) {
                // Exact: out_exact = vt - vt*vc/(vc+c_in), real-valued.
                // Ours rounds the remaining reserve UP, so out is <= exact.
                let remaining_floor = mul_div_floor(vt, vc, vc + c_in).unwrap();
                let out_if_rounded_the_wrong_way = vt - remaining_floor;
                assert!(out <= out_if_rounded_the_wrong_way,
                        "buy paid {out}, exceeding the favourable-rounding bound {out_if_rounded_the_wrong_way}");
            }
        }
    }
}

#[test]
fn a_buy_then_an_immediate_sell_never_profits() {
    // The round-trip property: rounding in both directions must cost the
    // trader, never the pool. This is what stops a dust-sized loop draining
    // a reserve one unit at a time.
    let mut c = Curve::new(10u128.pow(24), 10u128.pow(21), 10u128.pow(23)).unwrap();
    for c_in in [10u128.pow(12), 10u128.pow(15), 10u128.pow(18)] {
        let mut probe = c;
        let tokens = match probe.buy(c_in, 0) {
            Ok(t) => t,
            Err(_) => continue,
        };
        let back = match probe.sell(tokens, 0) {
            Ok(b) => b,
            Err(_) => continue,
        };
        assert!(
            back <= c_in,
            "round trip returned {back} for {c_in} in — the pool paid the trader to trade"
        );
    }
    let _ = c.buy(10u128.pow(15), 0);
}

#[test]
fn the_reserve_accounting_never_drifts() {
    struct Rng(u128);
    impl Rng {
        fn next(&mut self) -> u128 {
            let mut x = self.0;
            x ^= x << 23;
            x ^= x >> 17;
            x ^= x << 5;
            self.0 = x;
            x
        }
        fn below(&mut self, n: u128) -> u128 {
            if n == 0 {
                0
            } else {
                self.next() % n
            }
        }
    }
    let mut rng = Rng(0x0bad_c0de_0bad_c0de);
    let d = 10u128.pow(23);
    for _ in 0..300 {
        let mut c = Curve::new(10u128.pow(24), 10u128.pow(21), d).unwrap();
        let mut held: u128 = 0;
        let mut paid_in: u128 = 0;
        let mut paid_out: u128 = 0;
        for _ in 0..80 {
            if rng.next().is_multiple_of(2) {
                let amt = rng.below(10u128.pow(19)).max(1);
                if let Ok(out) = c.buy(amt, 0) {
                    held += out;
                    paid_in += amt
                }
            } else if held > 0 {
                let amt = rng.below(held).max(1);
                if let Ok(out) = c.sell(amt, 0) {
                    held -= amt;
                    paid_out += out
                }
            }
            // Tokens are conserved: what the pool no longer has, a trader holds.
            assert_eq!(c.sale_reserve + held, d, "token accounting drifted");
            // The pool never pays out more collateral than it took in.
            assert!(
                paid_out <= paid_in,
                "pool paid out {paid_out} having taken {paid_in}"
            );
            assert_eq!(
                c.real_collateral,
                paid_in - paid_out,
                "collateral accounting drifted"
            );
        }
    }
}

#[test]
fn dust_and_near_exhaustion() {
    let (vt, vc, d) = (10u128.pow(24), 10u128.pow(21), 10u128.pow(23));
    let c = Curve::new(vt, vc, d).unwrap();

    // A one-unit buy is priced by the spot rate, not rounded to nothing: at
    // Vc/Vt = 1e-3 one unit of collateral is worth about a thousand tokens,
    // and the implementation must return 999 rather than 1000 — the dust goes
    // to the pool. This assertion was wrong in the first version of this file
    // and the implementation was right; it is kept in this shape as the record.
    let one = c.quote_buy(1).unwrap();
    let exact_bound = vt - mul_div_floor(vt, vc, vc + 1).unwrap();
    assert!(
        one <= exact_bound && one > 0,
        "1-unit buy returned {one}, bound {exact_bound}"
    );

    // The whole sale reserve must be quotable, not overflow.
    assert!(c.quote_buy_exact_out(d).unwrap() > 0);

    // Beyond the sale reserve is refused by name, before any arithmetic.
    assert_eq!(
        c.quote_buy_exact_out(d + 1),
        Err(CurveError::ExceedsSaleReserve)
    );
}

#[test]
fn a_sell_can_never_drain_more_than_the_pool_holds() {
    let mut c = Curve::new(10u128.pow(24), 10u128.pow(21), 10u128.pow(23)).unwrap();
    let bought = c.buy(10u128.pow(18), 0).unwrap();
    match c.quote_sell(bought.saturating_mul(1_000)) {
        Err(CurveError::ExceedsRealCollateral) => {}
        Ok(v) => assert!(
            v <= c.real_collateral,
            "sell would pay {v} from {}",
            c.real_collateral
        ),
        Err(e) => panic!("unexpected {e:?}"),
    }
}

#[test]
fn slippage_refuses_before_state_moves() {
    let mut c = Curve::new(10u128.pow(24), 10u128.pow(21), 10u128.pow(23)).unwrap();
    let before = c;
    assert_eq!(
        c.buy(10u128.pow(18), u128::MAX),
        Err(CurveError::SlippageExceeded)
    );
    assert_eq!(c, before, "state moved on a refused buy");
}

#[test]
fn creation_refuses_a_curve_that_prices_its_last_token_at_infinity() {
    assert_eq!(
        Curve::new(100, 10, 100),
        Err(CurveError::VirtualTokenReserveTooSmall)
    );
    assert_eq!(Curve::new(0, 10, 5), Err(CurveError::ZeroAmount));
    assert!(Curve::new(101, 10, 100).is_ok());
}
