#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""The README's test count is what the suite actually passes.

    ./scripts/check-test-count.py                  # run the suite and compare
    cargo test --release 2>&1 | ./scripts/check-test-count.py -   # reuse a run

WHY THIS EXISTS

`README.md` opens by saying how many tests are green, and that number is quoted
outward — it is the shorthand a reader takes for how much of this is checked
rather than asserted. Nothing was comparing it to the suite. Adding a test left
the README a test short, and CI stayed green the whole time, because a suite that
grows does not fail: it just runs more tests than the sentence about it admits.

The count is what `cargo test` reports passing, summed across suites — not the
number of `#[test]` attributes in the tree. They agree here today, and they stop
agreeing the moment a test is `#[ignore]`d, generated by a macro, or compiled out
behind a feature. The one a reader can reproduce is the one cargo prints.

A SUITE THAT FAILS TO BUILD PASSES ZERO TESTS, and zero compared against a
sentence produces a confident mismatch about entirely the wrong thing. So a
non-zero exit from cargo is surfaced as itself, before any comparison.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULT = re.compile(r"^test result: ok\. (\d+) passed", re.M)
# The sentence this gate defends. Anchored on "tests green" rather than any
# number, so a README that drops the claim entirely fails here rather than
# passing by having nothing left to check.
CLAIM = re.compile(r"\b(\d+) tests green\b")


def main():
    readme = os.path.join(ROOT, "README.md")
    with open(readme, encoding="utf-8") as fh:
        text = fh.read()
    claims = CLAIM.findall(text)
    if not claims:
        print("README.md no longer says \"N tests green\" anywhere. That sentence is\n"
              "what this gate defends; without it there is nothing to compare the\n"
              "suite against, which is a silent loss of a check rather than a clean\n"
              "tree. Restore the claim or delete this gate deliberately.")
        return 1
    if len(set(claims)) > 1:
        print("README.md gives more than one test count: %s. A reader cannot tell\n"
              "which is the claim." % ", ".join(sorted(set(claims))))
        return 1
    claimed = int(claims[0])

    if len(sys.argv) > 1 and sys.argv[1] == "-":
        out = sys.stdin.read()
        rc = 0
    else:
        r = subprocess.run(["cargo", "test", "--release"], cwd=ROOT,
                           capture_output=True, text=True)
        out, rc = r.stdout + r.stderr, r.returncode
        if rc != 0:
            print("`cargo test --release` exited %d. A suite that does not build passes\n"
                  "zero tests, and zero against a README is a mismatch about the wrong\n"
                  "thing. The build is the failure here:\n" % rc)
            print("\n".join(out.strip().splitlines()[-12:]))
            return 1

    hits = [int(n) for n in RESULT.findall(out)]
    if not hits:
        print("no `test result: ok.` line was found in %d bytes of cargo output, so\n"
              "the suite total could not be read. That is a parsing failure, not a\n"
              "clean run." % len(out))
        return 1
    actual = sum(hits)
    print("README.md says %d tests green; the suite passes %d across %d suite(s)"
          % (claimed, actual, len(hits)))
    if actual != claimed:
        print("\nThey disagree. The README is the sentence a reader takes for how much\n"
              "of this is checked, and it is quoted outward, so it is the one that has\n"
              "to move. Update it to %d." % actual)
        return 1
    print("they agree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
