#!/usr/bin/env python3
"""Render evidence/VESTING.md from the replay log.

    scripts/render-vesting-evidence.py            # write it
    scripts/render-vesting-evidence.py --check    # fail if it is out of date

The log (evidence/vesting-replay.tsv) is what scripts/replay-vesting.sh wrote
while it drove the program on the public testnet: one line per call with its
verdict, and `#` lines for the balances and state it read back. This turns it
into the page a reader follows, in the order it happened. No hash in it is typed
by hand, and `--check` is how CI keeps it that way.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXPLORER = "https://explorer.testnet.lez.logos.co/transaction/"
REPO = "https://github.com/edenbd1/antumbra-lez"


def render() -> str:
    env = dict(l.split("=", 1) for l in (ROOT / "evidence/vesting-deploy.env").read_text().split())
    out = [
        "# antumbra_vesting on the public LEZ testnet",
        "",
        "Generated by `scripts/render-vesting-evidence.py` from",
        "[`vesting-replay.tsv`](vesting-replay.tsv), the log",
        "[`scripts/replay-vesting.sh`](../scripts/replay-vesting.sh) wrote while it drove",
        "the program. `./scripts/verify-onchain.sh --only vesting` re-checks every line",
        "against the sequencer: a landed call must resolve, a refused one must not.",
        "",
        "| | |",
        "|---|---|",
        f"| Program | `antumbra_vesting` |",
        f"| ImageID | `{env['IMAGE']}` |",
        f"| Deploy transaction | [`{env['DEPLOY_TX'][:8]}…{env['DEPLOY_TX'][-8:]}`]({EXPLORER}{env['DEPLOY_TX']}) |",
        f"| Block | {env['DEPLOY_BLOCK']} |",
        f"| Built from | [`{env['FREEZE'][:7]}`]({REPO}/commit/{env['FREEZE']}) |",
        "",
        "The deploy transaction's hash is `SHA256(u32_le(len) ‖ bytecode)` of",
        "`artifacts/programs/antumbra_vesting.bin`, so the committed file can be checked",
        "against the chain without an explorer.",
        "",
    ]
    table_open = False
    for line in (ROOT / "evidence/vesting-replay.tsv").read_text().splitlines():
        if line.startswith("#"):
            if table_open:
                out.append("")
                table_open = False
            text = line[1:].strip()
            if text.startswith("check ok: "):
                out.append(f"- ✅ {text[len('check ok: '):]}")
            else:
                out.append(f"- {text}")
            continue
        label, expect, verdict, block, h = line.split("\t")
        if not table_open:
            out += ["", "| call | outcome | block | transaction |", "|---|---|---|---|"]
            table_open = True
        if verdict == "LANDED":
            out.append(f"| `{label}` | landed | {block} | [`{h[:8]}…{h[-8:]}`]({EXPLORER}{h}) |")
        else:
            out.append(f"| `{label}` | **refused**, as required | — | `{h}` |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    path = ROOT / "evidence/VESTING.md"
    text = render()
    if "--check" in sys.argv:
        if not path.exists() or path.read_text() != text:
            print("evidence/VESTING.md is out of date; run scripts/render-vesting-evidence.py")
            return 1
        print("evidence/VESTING.md matches the replay log")
        return 0
    path.write_text(text)
    print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
