// SPDX-License-Identifier: MIT OR Apache-2.0
//! Fixed-point `pow` for the weighted-pool swap of
//! [RFP-016](https://github.com/logos-co/rfp/blob/master/RFPs/RFP-016-lbp-launchpad.md).
//!
//! The RFP's reference formula is
//!
//! ```text
//! tokens_out = Rt * (1 - (Rc / (Rc + C_in)) ^ (w_c / w_t))
//! ```
//!
//! and the exponent is a *rational* — a ratio of two weights that slide with
//! time. That is the one place this RFP is materially harder than RFP-015: the
//! bonding curve needs multiplication and division, this needs a fractional
//! power, in integer arithmetic, inside a zkVM where cycles are budgeted.
//!
//! `x^e = exp(e * ln x)`, computed at a scale of 1e18, with argument reduction
//! so both series converge fast enough to bound:
//!
//!   * `ln x` for x in (0, 1]: write x = m * 2^-k with m in [1, 2), then
//!     `ln x = ln m - k*ln2`, and `ln m = 2*atanh(z)` with z = (m-1)/(m+1).
//!     |z| <= 1/3, so the series loses a factor of 9 per term.
//!   * `exp(-y)` for y >= 0: write y = n*ln2 + r with r in [0, ln2), then
//!     `exp(-y) = 2^-n * exp(-r)`, and the Taylor series for r < 0.694 loses a
//!     factor of at least 1.4 per term and reaches the scale's last digit in
//!     about twenty.
//!
//! Both series are summed to a fixed term count chosen so the truncation error
//! is below the scale's resolution, and the whole result is rounded DOWN, which
//! is the direction that favours the pool: `tokens_out` must never round up.
//!
//! WHAT THIS DOES NOT CLAIM. The error bound below is an argument plus a
//! measured maximum over the differential vectors, not a machine-checked proof.
//! The vectors are generated by Python's `decimal` at 60 significant digits, so
//! the comparison is against arbitrary precision rather than against a second
//! copy of this code.

use crate::{mul_div_floor, CurveError, Result};

/// Fixed-point scale. One unit = 1e18, matching the platform convention.
pub const ONE: u128 = 1_000_000_000_000_000_000;

/// ln(2) at scale 1e18, truncated (not rounded) so reductions never overshoot.
const LN2: u128 = 693_147_180_559_945_309;

/// Terms in the atanh series.
///
/// The reduction leaves |z| <= 1/3, and z = 1/3 EXACTLY at x = 1/2 — the worst
/// case, reached by any halving. Term k falls as 9^-k, so the tail after n
/// terms is about (1/3)^(2n+1)/(2n+1). Twelve terms leaves 1e-13, which the
/// exponent then multiplies by up to 99; the measured worst error against the
/// Python vectors was 7e-12. Twenty-four terms puts the tail below 1e-19, at a
/// cost of twelve more 256-bit multiplications per call — the trade this
/// constant exists to make visible.
const ATANH_TERMS: u32 = 24;

/// Terms in the exp series for r < ln2.
const EXP_TERMS: u32 = 24;

/// `a * b / ONE`, rounded down, with the product taken in 256 bits.
#[inline]
fn mul(a: u128, b: u128) -> Result<u128> {
    mul_div_floor(a, b, ONE)
}

/// `a * ONE / b`, rounded down, with the product taken in 256 bits.
#[inline]
fn div(a: u128, b: u128) -> Result<u128> {
    if b == 0 {
        return Err(CurveError::ZeroAmount);
    }
    mul_div_floor(a, ONE, b)
}

/// -ln(x) for x in (0, ONE], at scale 1e18, rounded down.
///
/// Returned as a magnitude because the caller always negates it: for x <= 1 the
/// logarithm is non-positive, and carrying a sign through fixed point buys
/// nothing but a chance to drop it.
pub fn neg_ln(x: u128) -> Result<u128> {
    if x == 0 {
        return Err(CurveError::ZeroAmount);
    }
    if x > ONE {
        return Err(CurveError::QuantityAtOrAboveReserve);
    }
    if x == ONE {
        return Ok(0);
    }

    // Normalise into [ONE/2, ONE) rather than [ONE, 2*ONE), and the reason is
    // the whole precision story of this function.
    //
    // Reducing to [ONE, 2*ONE) gives -ln(x) = k*ln2 - ln(m), a SUBTRACTION of
    // two numbers that are both near 0.693 whenever x is near 1. For
    // x = 0.99974 the difference is 0.00025: three significant digits are
    // destroyed by cancellation before the exponent multiplies the error by
    // up to 99. The first version of this file did that and measured a worst
    // error of 7e-12 against the Python vectors.
    //
    // Reducing into [ONE/2, ONE) instead gives -ln(x) = k*ln2 + (-ln m) with
    // both terms non-negative. An addition cannot cancel.
    let half = ONE / 2;
    let mut m = x;
    let mut k: u32 = 0;
    while m < half {
        m = m.checked_mul(2).ok_or(CurveError::Overflow)?;
        k += 1;
    }
    // m in [ONE/2, ONE].  -ln(m) = 2*atanh(z), z = (ONE - m)/(ONE + m), z <= 1/3.
    let neg_ln_m = if m >= ONE {
        0
    } else {
        let z = div(ONE - m, ONE + m)?;
        let z2 = mul(z, z)?;
        let mut term = z;
        let mut sum = z;
        for i in 1..ATANH_TERMS {
            term = mul(term, z2)?;
            let d = (2 * i + 1) as u128;
            sum = sum.checked_add(term / d).ok_or(CurveError::Overflow)?;
        }
        sum.checked_mul(2).ok_or(CurveError::Overflow)?
    };

    let k_ln2 = LN2.checked_mul(k as u128).ok_or(CurveError::Overflow)?;
    k_ln2.checked_add(neg_ln_m).ok_or(CurveError::Overflow)
}

/// exp(-y) for y >= 0, at scale 1e18, rounded down.
pub fn exp_neg(y: u128) -> Result<u128> {
    if y == 0 {
        return Ok(ONE);
    }
    // y = n*ln2 + r, r in [0, ln2).
    let n = y / LN2;
    let r = y % LN2;
    if n >= 128 {
        // 2^-128 is far below the scale's resolution; the honest answer is 0.
        return Ok(0);
    }

    // exp(-r) by Taylor: sum (-r)^i / i!.
    // Kept as two running sums so no negative intermediate is needed.
    let mut term = ONE;
    let mut pos = ONE;
    let mut neg = 0u128;
    for i in 1..EXP_TERMS {
        term = mul(term, r)? / i as u128;
        if term == 0 {
            break;
        }
        if i % 2 == 1 {
            neg = neg.checked_add(term).ok_or(CurveError::Overflow)?;
        } else {
            pos = pos.checked_add(term).ok_or(CurveError::Overflow)?;
        }
    }
    let e = pos.checked_sub(neg).ok_or(CurveError::Overflow)?;

    Ok(e >> n)
}

/// `x ^ (num / den)` for x in (0, ONE] and a positive rational exponent.
///
/// Rounded DOWN. In the swap formula the result is subtracted from ONE, so
/// rounding the power down rounds `tokens_out` down — the pool keeps the dust,
/// which is the invariant this whole crate is organised around.
pub fn pow_frac(x: u128, num: u128, den: u128) -> Result<u128> {
    if den == 0 {
        return Err(CurveError::ZeroAmount);
    }
    if x == ONE {
        return Ok(ONE);
    }
    if num == den {
        // x^(n/n) = x, exactly. Not a shortcut: an LBP sits at equal weights
        // whenever its schedule crosses 50/50, and routing that through
        // exp(ln(x)) would return x plus a rounding error for no reason.
        return Ok(x);
    }
    let nl = neg_ln(x)?;
    // e * (-ln x), with the ratio applied before the exponential so the
    // rational exponent never becomes a fixed-point division of its own.
    let scaled = mul_div_floor(nl, num, den)?;
    exp_neg(scaled)
}

/// The RFP-016 swap: tokens out for `c_in` collateral, given reserves and the
/// weights in force at this block.
///
/// `tokens_out = Rt * (1 - (Rc/(Rc+C_in)) ^ (w_c/w_t))`, rounded down.
pub fn weighted_buy(
    reserve_token: u128,
    reserve_collateral: u128,
    c_in: u128,
    w_token: u128,
    w_collateral: u128,
) -> Result<u128> {
    if c_in == 0 || reserve_token == 0 || reserve_collateral == 0 {
        return Err(CurveError::ZeroAmount);
    }
    if w_token == 0 || w_collateral == 0 {
        return Err(CurveError::ZeroAmount);
    }
    let denom = reserve_collateral
        .checked_add(c_in)
        .ok_or(CurveError::Overflow)?;
    let base = div(reserve_collateral, denom)?; // in (0, ONE)
    let p = pow_frac(base, w_collateral, w_token)?;
    let one_minus = ONE.checked_sub(p).ok_or(CurveError::Overflow)?;
    let out = mul_div_floor(reserve_token, one_minus, ONE)?;
    if out > reserve_token {
        return Err(CurveError::ExceedsSaleReserve);
    }
    Ok(out)
}

/// Linear weight interpolation, computed lazily from the block timestamp.
///
/// The RFP requires the correct weight at transaction time "regardless of how
/// recently the last poke occurred", so nothing is stored and refreshed: the
/// weight is a function of `now` and the schedule, evaluated on each call.
pub fn weight_at(
    w_start: u128,
    w_end: u128,
    t_start: u64,
    t_end: u64,
    now: u64,
) -> Result<u128> {
    if t_end <= t_start {
        return Err(CurveError::ZeroAmount);
    }
    if now <= t_start {
        return Ok(w_start);
    }
    if now >= t_end {
        return Ok(w_end);
    }
    let elapsed = (now - t_start) as u128;
    let span = (t_end - t_start) as u128;
    if w_end >= w_start {
        let delta = mul_div_floor(w_end - w_start, elapsed, span)?;
        w_start.checked_add(delta).ok_or(CurveError::Overflow)
    } else {
        let delta = mul_div_floor(w_start - w_end, elapsed, span)?;
        w_start.checked_sub(delta).ok_or(CurveError::Overflow)
    }
}
